name: Attack Lab CI
on:
  push:
  pull_request:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  
  job-4_25:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install gdb
    - name: Execute Codes
      run: |
        ddl=`date -d "2022-11-20 15:59" +%s --utc`
        current_time=`date +%s`
        [ $current_time -le $ddl ]
        set -x
        cd ./lab4/attack-handout
        cd ./25
        cat answer1.txt | ./hex2raw > answer1_raw1.txt
        gdb ctarget -ex 'run -q < answer1_raw1.txt'
        rm -f answer1_raw1.txt
        cat answer2.txt | ./hex2raw > answer2_raw2.txt
        gdb ctarget -ex 'run -q < answer2_raw2.txt'
        rm -f answer2_raw2.txt
      
