name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Install dependencies
      run: |
        cd https://github.com/zjpedu/Computer-Systems-Labs/tree/main/lab2/datalab-handout
        make
        ./btest

