name: CSAPP PULL REQUEST CI

on:
  pull request:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute Codes
      run: |
        cd ./lab1
        chmod a+x ./*
        touch test.txt
        chmod 777 test.txt
        for i in `ls -al .`; do if [ -f $i ];then ./$i; fi; done
